### ISSUE TITLE
List gini/puppet-gradle on Puppet Forge?

### ISSUE THREAD

**Issue by sghill** [gini/puppet-gradle#6]
Hello :)

I've recently been working more with puppet. I found this project by [searching Puppet Forge for gradle](http://forge.puppetlabs.com/modules?utf-8=%E2%9C%93&q=gradle).

The only project returned is [smarchive/puppet-gradle](https://github.com/smarchive/puppet-gradle). After jumping through to the github page, I found out the project has been moved to gini/puppet-gradle. I'm assuming this means that any pull requests accepted into the current home won't be published to smarchive/puppet-gradle.

It'd be really awesome if:
1. Puppet Forge had a listing for gini/puppet-gradle
2. Puppet Forge had an updated smarchive/puppet-gradle that indicated the new home of the project is gini/puppet-gradle

Thanks for the consideration!

**Comment by dkerwin** [comment]
Thanks. We will republish it once all the PRs are merged

**Comment by joschi** [comment]
Thanks for the feedback, Steve! We just released a new version of the Gradle module to the forge.

http://forge.puppetlabs.com/gini/gradle/0.2.0
